export const cameraInjectionKey = Symbol('cameraInjectionKey')
export const sceneInjectionKey = Symbol('sceneInjectionKey')
export const sceneRefInjectionKey = Symbol('sceneRefInjectionKey')
export const meshInjectionKey = Symbol('meshInjectionKey')
export const boxGeometryInjectionKey = Symbol('boxGeometryInjectionKey')
export const rendererInjectionKey = Symbol('rendererInjectionKey')
