export const PKG_PREFIX = '@farst-three'
export const PKG_NAME = 'farst-three'
export const PKG_CAMELCASE_NAME = 'FarstThree'
export const PKG_CAMELCASE_LOCAL_NAME = 'FarstThreeLocale'
export const PKG_BRAND_NAME = 'farst-three'
