export const PKG_PREFIX = '@farst-three'
export const PKG_NAME = 'farst-three'
export const PKG_CAMELCASE_NAME = 'ElementPlus'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'farst-three'
